[package]
name = "wikipedia_game_rust"
version = "0.1.0"
authors = ["nathancohen4299 <ncohen4299@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.11.0"
curl = "0.4.25"
